package aggr

import (
	"errors"
	"fmt"
	"time"

	"poprako-s/internal/domain/model/enum"
)

// `Chapter` represents one chapter inside a comic
// It contains workflow timestamps and pinned state
// Mutable workflow fields are advanced by `TransiteWorkflow`
// Relation fields are include-driven
// Time pointers keep nullable database semantics
type Chapter struct {
	// `Id` is chapter identifier
	Id string

	// `ComicId` is owner comic identifier
	ComicId string
	// `Comic` is included only when includes contain `comic`
	Comic *Comic

	// `IsPinned` indicates whether this chapter is pinned in comic
	IsPinned bool

	// `Index` is comic-scoped chapter order
	Index int
	// `Subtitle` is chapter subtitle
	Subtitle string

	// `PageCount` is chapter page count
	PageCount int
	// `TotalUnitCount` is total translation unit count
	TotalUnitCount int
	// `TranslatedUnitCount` is translated unit count
	TranslatedUnitCount int
	// `ProofreadUnitCount` is proofread unit count
	ProofreadUnitCount int

	// `CreatorId` is chapter creator user identifier
	CreatorId string
	// `Creator` is included only when includes contain `creator`.
	Creator *User

	// `CreatedAt` is creation timestamp
	CreatedAt time.Time
	// `UpdatedAt` is update timestamp
	UpdatedAt time.Time

	// Workflow timestamps.
	UploadedAt *time.Time

	TransalatingAt *time.Time
	TranslatedAt   *time.Time

	ProofreadingAt *time.Time
	ProofreadAt    *time.Time

	TypesettingAt *time.Time
	TypesetAt     *time.Time

	ReviewedAt  *time.Time
	PublishedAt *time.Time
}

// `TransiteWorkflow` applies a workflow transition to chapter state.
func (c *Chapter) TransiteWorkflow(t enum.WorkflowTransition) error {
	now := time.Now()

	markStarted := func(
		startedAt **time.Time,
		completedAt *time.Time,
		ongoingMsg string,
		completedMsg string,
	) error {
		if completedAt != nil {
			return errors.New(completedMsg)
		}

		if *startedAt != nil {
			return errors.New(ongoingMsg)
		}

		*startedAt = &now

		return nil
	}

	markCompleted := func(
		startedAt *time.Time,
		completedAt **time.Time,
		pendingMsg string,
		completedMsg string,
	) error {
		if *completedAt != nil {
			return errors.New(completedMsg)
		}

		if startedAt == nil {
			return errors.New(pendingMsg)
		}

		*completedAt = &now

		return nil
	}

	markOnce := func(completedAt **time.Time, completedMsg string) error {
		if *completedAt != nil {
			return errors.New(completedMsg)
		}

		*completedAt = &now

		return nil
	}

	switch t {
	case enum.WorkflowUploadComplete:
		if err := markOnce(&c.UploadedAt, "上传进度已经标记为完成"); err != nil {
			return err
		}

	case enum.WorkflowTranslateStart:
		if err := markStarted(
			&c.TransalatingAt,
			c.TranslatedAt,
			"翻译进度已经处于进行中",
			"翻译进度已经标记为完成",
		); err != nil {
			return err
		}

	case enum.WorkflowTranslateComplete:
		if err := markCompleted(
			c.TransalatingAt,
			&c.TranslatedAt,
			"翻译进度尚未开始",
			"翻译进度已经标记为完成",
		); err != nil {
			return err
		}

	case enum.WorkflowProofreadStart:
		if err := markStarted(
			&c.ProofreadingAt,
			c.ProofreadAt,
			"校对进度已经处于进行中",
			"校对进度已经标记为完成",
		); err != nil {
			return err
		}

	case enum.WorkflowProofreadComplete:
		if err := markCompleted(
			c.ProofreadingAt,
			&c.ProofreadAt,
			"校对进度尚未开始",
			"校对进度已经标记为完成",
		); err != nil {
			return err
		}

	case enum.WorkflowTypesetStart:
		if err := markStarted(
			&c.TypesettingAt,
			c.TypesetAt,
			"嵌字进度已经处于进行中",
			"嵌字进度已经标记为完成",
		); err != nil {
			return err
		}

	case enum.WorkflowTypesetComplete:
		if err := markCompleted(
			c.TypesettingAt,
			&c.TypesetAt,
			"嵌字进度尚未开始",
			"嵌字进度已经标记为完成",
		); err != nil {
			return err
		}

	case enum.WorkflowReviewComplete:
		if err := markOnce(&c.ReviewedAt, "监修进度已经标记为完成"); err != nil {
			return err
		}

	case enum.WorkflowPublishComplete:
		if err := markOnce(&c.PublishedAt, "发布进度已经标记为完成"); err != nil {
			return err
		}

	default:
		return fmt.Errorf("unknown workflow transition: %s", t)
	}

	return nil
}

// `ChapterCre` holds creation payload for chapter insert.
type ChapterCre struct {
	// `Id` is generated by chapter service
	Id string

	// `ComicId` is owner comic identifier
	ComicId string
	// `Index` is comic-scoped chapter index
	Index int
	// `Subtitle` is optional subtitle and defaults to `Ch.<index>` when nil
	Subtitle *string

	// `CreatorId` is chapter creator user identifier
	CreatorId string
}

// `ChapterUpd` holds mutable fields for chapter update.
// Optional fields are patch-like and applied only when selected.
// Workflow fields use pointer-to-pointer to distinguish skip (nil) from
// an explicit nullable write (&nil means write NULL; &ptr means write *ptr).
// `Id` identifies the target chapter.
type ChapterUpd struct {
	// `Id` identifies target chapter.
	Id string

	// `Subtitle` is optional subtitle update.
	Subtitle *string
	// `IsPinned` optionally updates pinned status.
	IsPinned *bool

	// `UploadedAt` is the upload completion timestamp update.
	UploadedAt **time.Time
	// `TransalatingAt` is the translate-start timestamp update.
	TransalatingAt **time.Time
	// `TranslatedAt` is the translate-complete timestamp update.
	TranslatedAt **time.Time
	// `ProofreadingAt` is the proofread-start timestamp update.
	ProofreadingAt **time.Time
	// `ProofreadAt` is the proofread-complete timestamp update.
	ProofreadAt **time.Time
	// `TypesettingAt` is the typeset-start timestamp update.
	TypesettingAt **time.Time
	// `TypesetAt` is the typeset-complete timestamp update.
	TypesetAt **time.Time
	// `ReviewedAt` is the review-complete timestamp update.
	ReviewedAt **time.Time
	// `PublishedAt` is the publish-complete timestamp update.
	PublishedAt **time.Time
}
