package aggr

import "time"

type Unit struct {
	Id string

	PageId string
	Index  int

	IsBubble    bool
	IsProofread bool

	XCoord float64
	YCoord float64

	TranslatedText    *string
	TranslatorComment *string
	LastTranslatorId  *string

	ProofreadText      *string
	ProofreaderComment *string
	LastProofreaderId  *string

	CreatedAt time.Time
	UpdatedAt time.Time
}

type UnitDiff struct {
	PageId    string
	Ops       []UnitOp
	CandOrder []string
}

// `UnitCre` represents a unit creation operation.
// It contains all fields of `Unit` except `Id`, which is generated by database.
type UnitCre struct {
	// `LocalId` is a temporary identifier generated by client to identify the unit before database generates `Id`.
	// It is used in CandOrder to provide with a sample order of units from
	// the sender client.
	LocalId string

	PageId string

	IsBubble    bool
	IsProofread bool

	XCoord float64
	YCoord float64

	TranslatedText    *string
	TranslatorComment *string
	LastTranslatorId  *string

	ProofreadText      *string
	ProofreaderComment *string
	LastProofreaderId  *string
}

func (*UnitCre) UnitOpMark() {}

// `UnitSave` represents a unit **PUT/UPSERT** operation.
// If client has modified a unit, it should send a `UnitSave` op with all fields of the unit
// as it may be deleted before the modification, and the server will re-construct
// the unit with the provided fields.
type UnitSave struct {
	Id string

	PageId string

	IsBubble    bool
	IsProofread bool

	XCoord float64
	YCoord float64

	TranslatedText    *string
	TranslatorComment *string
	LastTranslatorId  *string

	ProofreadText      *string
	ProofreaderComment *string
	LastProofreaderId  *string
}

func (*UnitSave) UnitOpMark() {}

type UnitDel struct {
	Id string
}

func (*UnitDel) UnitOpMark() {}

type UnitIndex struct {
	Id    string
	Index int
}
