package aggr

import "time"

type Unit struct {
	Id string

	PageId string
	Index  int

	IsBubble    bool
	IsProofread bool

	XCoord float64
	YCoord float64

	TranslatedText    *string
	TranslatorComment *string
	LastTranslatorId  *string

	ProofreadText      *string
	ProofreaderComment *string
	LastProofreaderId  *string

	CreatedAt time.Time
	UpdatedAt time.Time
}

// `hasUnitText` reports whether one optional unit text field stores meaningful content.
func hasUnitText(text *string) bool {
	return text != nil && *text != ""
}

// `IsTranslated` reports whether the unit stores translated content.
// Proofread text also counts because it is still translated text content.
func (u *Unit) IsTranslated() bool {
	return hasUnitText(u.TranslatedText) || hasUnitText(u.ProofreadText)
}

// `IsProofreaded` reports whether the unit has reached proofread state.
func (u *Unit) IsProofreaded() bool {
	return u.IsProofread
}

type UnitTranProfState struct {
	Translated bool
	Proofread  bool
}

type UnitDiff struct {
	PageId    string
	Ops       []UnitOp
	CandOrder []string
}

// `UnitCre` represents a unit creation operation.
// It contains all fields of `Unit` except `Id`, which is generated by database.
type UnitCre struct {
	// `LocalId` is a temporary identifier generated by client to identify the unit before database generates `Id`.
	// It is used in CandOrder to provide with a sample order of units from
	// the sender client.
	LocalId string

	PageId string

	IsBubble    bool
	IsProofread bool

	XCoord float64
	YCoord float64

	TranslatedText    *string
	TranslatorComment *string
	LastTranslatorId  *string

	ProofreadText      *string
	ProofreaderComment *string
	LastProofreaderId  *string
}

func (*UnitCre) UnitOpMark() {}

// `UnitSave` represents a unit **PUT/UPSERT** operation.
// If client has modified a unit, it should send a `UnitSave` op with all fields of the unit
// as it may be deleted before the modification, and the server will re-construct
// the unit with the provided fields.
type UnitSave struct {
	Id string

	PageId string

	IsBubble    bool
	IsProofread bool

	XCoord float64
	YCoord float64

	TranslatedText    *string
	TranslatorComment *string
	LastTranslatorId  *string

	ProofreadText      *string
	ProofreaderComment *string
	LastProofreaderId  *string
}

func (*UnitSave) UnitOpMark() {}

type UnitDel struct {
	Id string
}

func (*UnitDel) UnitOpMark() {}

type UnitIndex struct {
	Id    string
	Index int
}
