// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "使用 QQ 和密码进行登录，成功返回访问令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "用户登录（已测试）",
                "parameters": [
                    {
                        "description": "登录参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/value.LoginUserArgs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/value.LoginUserResult"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "使用 QQ、密码、名字和邀请码进行注册，成功返回访问令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/value.RegisterUserArgs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/value.RegisterUserResult"
                        }
                    }
                }
            }
        },
        "/invitations": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取指定汉化组的邀请列表，注意当列表为空，会返回 null 而不是空数组",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "invitation"
                ],
                "summary": "获取邀请列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "汉化组 ID",
                        "name": "team_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/value.InvitationInfo"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "在指定汉化组中创建一个新的邀请",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "invitation"
                ],
                "summary": "创建邀请",
                "parameters": [
                    {
                        "description": "创建邀请参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/value.CreateInvitationArgs"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/value.InvitationInfo"
                        }
                    }
                }
            }
        },
        "/invitations/{invitation_id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除指定的邀请",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "invitation"
                ],
                "summary": "删除邀请",
                "parameters": [
                    {
                        "type": "string",
                        "description": "邀请 ID",
                        "name": "invitation_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "更新指定邀请的信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "invitation"
                ],
                "summary": "更新邀请",
                "parameters": [
                    {
                        "type": "string",
                        "description": "邀请 ID",
                        "name": "invitation_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新邀请参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/value.UpdateInvitationArgs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/members": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取指定汉化组的成员列表，注意当列表为空，会返回 null 而不是空数组",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "member"
                ],
                "summary": "获取指定汉化组的成员列表（已测试）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "汉化组 ID",
                        "name": "team_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "偏移量",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/value.MemberProfile"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "由超级管理员直接创建成员记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "member"
                ],
                "summary": "创建成员（已测试）",
                "parameters": [
                    {
                        "description": "创建成员参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/value.CreateMemberArgs"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/value.CreateMemberResult"
                        }
                    }
                }
            }
        },
        "/members/join": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "已登录用户使用邀请码加入对应汉化组",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "member"
                ],
                "summary": "通过邀请码加入汉化组",
                "parameters": [
                    {
                        "description": "加入勇化组参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/value.JoinTeamArgs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/members/{member_id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "从汉化组中移除指定成员",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "member"
                ],
                "summary": "移除成员",
                "parameters": [
                    {
                        "type": "string",
                        "description": "成员 ID",
                        "name": "member_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "更新指定成员的分工角色",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "member"
                ],
                "summary": "更新成员角色",
                "parameters": [
                    {
                        "type": "string",
                        "description": "成员 ID",
                        "name": "member_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新成员角色参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/value.UpdateMemberRoleArgs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/teams": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取所有汉化组列表，仅超级管理员有权限，注意当列表为空，会返回 null 而不是空数组",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "team"
                ],
                "summary": "获取所有汉化组列表（已测试）",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/value.TeamInfo"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "创建一个新的汉化组，仅超级管理员有权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "team"
                ],
                "summary": "创建汉化组（已测试）",
                "parameters": [
                    {
                        "description": "创建汉化组参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/value.CreateTeamArgs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/value.TeamInfo"
                        }
                    }
                }
            }
        },
        "/teams/mine": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取当前用户所在的汉化组列表，注意当列表为空，会返回 null 而不是空数组",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "team"
                ],
                "summary": "获取当前用户所在的汉化组列表（已测试）",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/value.TeamInfo"
                            }
                        }
                    }
                }
            }
        },
        "/teams/{team_id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除指定汉化组，超级管理员或汉化组管理员有权限",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "team"
                ],
                "summary": "删除汉化组",
                "parameters": [
                    {
                        "type": "string",
                        "description": "汉化组 ID",
                        "name": "team_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "更新指定汉化组的信息，超级管理员或汉化组管理员有权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "team"
                ],
                "summary": "更新汉化组信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "汉化组 ID",
                        "name": "team_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新汉化组参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/value.UpdateTeamArgs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据查询条件获取用户列表，支持按 QQ、模糊名称筛选，注意当列表为空，会返回 null 而不是空数组",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "获取用户列表（已测试）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "QQ 号",
                        "name": "qq",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "模糊名称",
                        "name": "fuzzy_name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "偏移量",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/value.UserInfo"
                            }
                        }
                    }
                }
            }
        },
        "/users/{user_id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据用户 ID 获取用户详细信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "根据 ID 获取用户信息（已测试）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户 ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/value.UserInfo"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据用户 ID 删除用户",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户 ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "util.Option-string": {
            "type": "object"
        },
        "value.CreateInvitationArgs": {
            "type": "object",
            "properties": {
                "invitee_qq": {
                    "type": "string"
                },
                "roles": {
                    "type": "integer"
                },
                "team_id": {
                    "type": "string"
                }
            }
        },
        "value.CreateMemberArgs": {
            "type": "object",
            "properties": {
                "roles": {
                    "type": "integer"
                },
                "team_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "value.CreateMemberResult": {
            "type": "object",
            "properties": {
                "member_id": {
                    "type": "string"
                }
            }
        },
        "value.CreateTeamArgs": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "value.InvitationInfo": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "invitation_code": {
                    "type": "string"
                },
                "invitee_qq": {
                    "type": "string"
                },
                "invitor_id": {
                    "type": "string"
                },
                "pending": {
                    "type": "boolean"
                },
                "roles": {
                    "type": "integer"
                }
            }
        },
        "value.JoinTeamArgs": {
            "type": "object",
            "properties": {
                "invitation_code": {
                    "type": "string"
                }
            }
        },
        "value.LoginUserArgs": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "qq": {
                    "type": "string"
                }
            }
        },
        "value.LoginUserResult": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "value.MemberProfile": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "created_at": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "qq": {
                    "type": "string"
                },
                "roles": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "integer"
                }
            }
        },
        "value.RegisterUserArgs": {
            "type": "object",
            "properties": {
                "invitation_code": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "qq": {
                    "type": "string"
                }
            }
        },
        "value.RegisterUserResult": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "value.TeamInfo": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "integer"
                }
            }
        },
        "value.UpdateInvitationArgs": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "roles": {
                    "type": "integer"
                },
                "team_id": {
                    "type": "string"
                }
            }
        },
        "value.UpdateMemberRoleArgs": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "roles": {
                    "type": "integer"
                }
            }
        },
        "value.UpdateTeamArgs": {
            "type": "object",
            "properties": {
                "description": {
                    "$ref": "#/definitions/util.Option-string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "$ref": "#/definitions/util.Option-string"
                }
            }
        },
        "value.UserInfo": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "created_at": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "qq": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "LabelPlus Next Web API",
	Description:      "LabelPlus Next Web 后端 API 文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
