package aggr

import "time"

// `Comic` represents one manga title inside a workset
// It is soft-deletable and only rows with nil `DeletedAt` are active in repo query
// Relation fields are optional and loaded by typed includes
// Mutable fields are updated by `ComicUpd` with put semantics
// Time fields are plain domain timestamps without transport formatting
type Comic struct {
	// `Id` is the unique identifier of the comic
	Id string

	// `WorksetId` is the owning workset identifier
	WorksetId string
	// `Workset` is included only when includes contain `workset`
	Workset *Workset

	// `Index` is the workset-scoped position of this comic
	Index int

	// `Title` is the comic title
	Title string
	// `Author` is the comic author
	Author string
	// `Desc` is the optional comic description
	Desc *string
	// `IsCompleted` marks whether the comic has completed its lifecycle.
	IsCompleted bool

	// `ChapterCount` is the denormalized chapter counter
	ChapterCount int

	// `CreatorId` is the user identifier who created this comic
	CreatorId string

	// `LastActiveAt` tracks the latest activity timestamp
	LastActiveAt time.Time
	// `CreatedAt` is the creation timestamp
	CreatedAt time.Time
	// `UpdatedAt` is the last update timestamp
	UpdatedAt time.Time
}

// `ComicCre` holds the input fields required to create a comic
// `Id` and `Index` are prepared before persistence
// `Desc` keeps nullable semantics from migration
type ComicCre struct {
	// `Id` is generated by domain service
	Id string

	// `WorksetId` is the owning workset identifier
	WorksetId string
	// `Index` is the workset-scoped sequence index
	Index int

	// `Title` is the display title
	Title string
	// `Author` is the author name
	Author string
	// `Desc` is the optional description
	Desc *string

	// `CreatorId` is the creator user identifier
	CreatorId string
}

// `ComicUpd` carries mutable fields for updating a comic
// Nil `Desc` means writing SQL NULL under put semantics
// `Id` identifies the target comic row
// This keeps update input explicit and stable across layers
type ComicUpd struct {
	// `Id` identifies the comic to update
	Id string

	// `Title` is the new title
	Title string
	// `Author` is the new author
	Author string
	// `Desc` is the new description and nil writes SQL NULL
	Desc *string
}
