package aggr

import (
	"fmt"
	"time"

	"poprako-s/internal/domain/model/event"
	event_iface "poprako-s/internal/event"

	"golang.org/x/crypto/bcrypt"
)

type UserToken struct {
	UserId string
}

type User struct {
	Id string

	Nickname string
	Qid      string

	AvatarKey      string
	AvatarUploaded bool

	IsSuperAdmin bool

	LastActiveAt time.Time

	CreatedAt time.Time
	UpdatedAt time.Time
}

// `GenToken` generates infomation for a token.
func (u *User) GenToken() UserToken {
	return UserToken{UserId: u.Id}
}

func (u *User) GenAvatarKey(ext string) string {
	return fmt.Sprintf("user_avatar/%s.%s", u.Id, ext)
}

type UserCreds struct {
	// Embedded for domain events:
	// - UserLoginEv: update LastActiveAt
	event_iface.EvBase

	Id      string
	PwdHash string
}

func (c *UserCreds) VerifyPwd(pwd string) error {
	// Compare password hash and raw password.
	if err := bcrypt.CompareHashAndPassword(
		[]byte(c.PwdHash),
		[]byte(pwd),
	); err != nil {
		return fmt.Errorf("[UserCreds.VerifyPwd] unmatched password: %w", err)
	}

	c.PushEv(event.NewUserLoginEv(c.Id))

	return nil
}

type UserReg struct {
	// Embedded for domain events:
	// - UserRegEv: notify invitor
	event_iface.EvBase

	// `Id` should be generated by service layer,
	// not repo layer.
	Id string

	Qid      string
	Nickname string

	// Password should be hashed in service layer.
	PwdHash string
}

// `UserUpd` contains info to **replace** original user info.
// NOTE: it has **PUT** sementics.
type UserUpd struct {
	Id string

	Qid  string
	Name string
}
