package aggr

import (
	"fmt"
	"time"

	"poprako-s/internal/domain/model/event"
	event_iface "poprako-s/internal/event"

	"golang.org/x/crypto/bcrypt"
)

// `UserToken` holds the minimal claim set used when generating or parsing
// a signed token for a user
type UserToken struct {
	// `UserId` is the unique identifier of the token owner
	UserId string
}

// `User` represents a registered application user
type User struct {
	Id string

	Nickname string
	Qid      string

	// `AvatarKey` holds the OSS object key for the user avatar
	AvatarKey string
	// `AvatarUploaded` is true when the avatar has been confirmed uploaded by the client
	AvatarUploaded bool

	IsSuperAdmin bool

	LastActiveAt time.Time

	CreatedAt time.Time
	UpdatedAt time.Time
}

// `GenToken` generates infomation for a token.
func (u *User) GenToken() UserToken {
	return UserToken{UserId: u.Id}
}

// `GenAvatarKey` returns the OSS object key for the user avatar with the given file extension
func (u *User) GenAvatarKey(ext string) string {
	return fmt.Sprintf("user_avatar/%s.%s", u.Id, ext)
}

// `UserCreds` holds the minimal credential data needed for password-based authentication
type UserCreds struct {
	// Embedded for domain events:
	// - UserLoginEv: update LastActiveAt
	event_iface.EvBase

	Id      string
	PwdHash string
}

// `VfyPwd` verifies the raw password against the stored hash and emits a login event on success
func (c *UserCreds) VfyPwd(pwd string) error {
	// Compare password hash and raw password.
	if err := bcrypt.CompareHashAndPassword(
		[]byte(c.PwdHash),
		[]byte(pwd),
	); err != nil {
		return fmt.Errorf("[UserCreds.VfyPwd] unmatched password: %w", err)
	}

	c.PushEv(event.NewUserLoginEv(c.Id))

	return nil
}

// `UserReg` represents the input required to register a new user
type UserReg struct {
	// Embedded for domain events:
	// - UserRegEv: notify invitor
	event_iface.EvBase

	// `Id` should be generated by service layer,
	// not repo layer.
	Id string

	Qid      string
	Nickname string

	// Password should be hashed in service layer.
	PwdHash string
}

// `UserUpd` contains info to **replace** original user info.
// NOTE: it has **PUT** sementics.
type UserUpd struct {
	Id string

	Qid  string
	Name string
}
