package aggr

import "time"

// `Workset` represents a collection of comics owned by a team.
type Workset struct {
	// `Id` is the unique identifier for this workset.
	Id string

	// `TeamId` is the owning team's identifier.
	TeamId string
	// `Team` is included only when `includes` contains `team`
	Team *Team

	// `Index` is the team-scoped position of this workset.
	// Active worksets within a team must have unique indices.
	Index int

	// `Name` is the human-readable title of the workset.
	Name string
	// `Desc` is an optional description of the workset.
	Desc *string
	// `ComicCount` is the number of comics in this workset.
	ComicCount int

	// `CreatedAt` is the creation timestamp.
	CreatedAt time.Time

	// `UpdatedAt` is the last-modification timestamp.
	UpdatedAt time.Time
}

// `WorksetCre` holds the input needed to create a new workset.
type WorksetCre struct {
	// `Id` is generated by the domain service.
	Id string

	// `TeamId` is the owning team's identifier.
	TeamId string
	// `Index` is the team-scoped position, pre-computed by the caller
	// as the count of active worksets before this insert.
	Index int

	// `Name` is the display title.
	Name string
	// `Desc` is an optional description.
	Desc *string
}

// `WorksetUpd` carries the mutable fields for a workset update.
// A nil `Desc` means the description should not be changed.
type WorksetUpd struct {
	// `Id` identifies the workset to update.
	Id string

	// `Name` is the new display title.
	Name string
	// `Desc` is the new description for `PUT` semantics.
	// Nil means the description will be set to SQL `NULL`.
	Desc *string
}
